### ISSUE TITLE
EKS compatible?

### ISSUE THREAD

**Issue by offzale** [coredns/kubernetai#20]
Just tried to make it work with an EKS remote cluster, no success. I am getting an unauthorized error response from k8s api-server.
```
E0319 07:09:59.530761       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Unauthorized
```

This is my coredns kubernetai config (replaced kubernetes default block), the rest is coredns defaults
```
kubernetai cluster.local {
      kubeconfig /tmp/coredns/kubeconfig.yaml remote
      namespaces eu-central-1-b
      fallthrough
}
kubernetai cluster.local {
      pods insecure
      upstream
      fallthrough in-addr.arpa ip6.arpa
}
```

kubeconfig.yaml
```
apiVersion: v1
clusters:
- cluster:
    # I was getting another error when setting EKS cluster's CA, so I enabled insecure mode to test
    insecure-skip-tls-verify: true
    server: https://bla.sk1.eu-central-1.eks.amazonaws.com
  name: remote
contexts:
- context:
    cluster: remote
    namespace: default
    user: remote
  name: remote
current-context: ""
kind: Config
preferences: {}
users:
- name: remote
  user:
    client-certificate: cert.pem
    client-key: key.pem
```

Client key and certificate are self-signed and added to the user in AWS with permissions to operate the cluster.

Am I missing anything? Or the plugin is not compatible with EKS yet?

Thank you :)
